# Generated by Django 3.0.3 on 2020-08-06 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('denomination', models.CharField(choices=[('Baptist', 'Baptist'), ('Catholic', 'Catholic'), ('Nondenominational', 'Nondenominational'), ('Orthodox', 'Orthodox'), ('Angelican', 'Angelican'), ('Methodist', 'Methodist'), ('Lutheran', 'Lutheran'), ('Anabaptist', 'Anabaptist'), ('Adventist', 'Adventist'), ('Assemblies of God', 'Assemblies of God'), ('Penecostalism', 'Penecostalism'), ('Calvinism', 'Calvinism'), ('Presbyterian', 'Presbyterian'), ('Anglican', 'Anglican'), ('Church of God', 'Church of God'), ('Church of the Nazarene', 'Church of the Nazarene'), ('Assyrian', 'Assyrian'), ('Church of England', 'Church of England')], default='Prefer not to say', max_length=32)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
