# Generated by Django 3.0.3 on 2020-08-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200810_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='hidden_talent',
            new_name='bible_verse',
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, default='not', max_length=13),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, default='available', max_length=13),
        ),
    ]
