# Generated by Django 3.0.3 on 2020-08-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200815_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='testimony',
        ),
        migrations.AddField(
            model_name='profile',
            name='image_eight',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_five',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_seven',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_six',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_pics'),
        ),
    ]
