# Generated by Django 3.0.3 on 2020-08-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200816_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='testimony',
            field=models.TextField(default='Not Available', max_length=300),
        ),
    ]
