# Generated by Django 3.0.3 on 2020-08-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200818_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_one',
            field=models.ImageField(blank=True, help_text='Note: when updating any of your 8 gallery pictures, it is best to upload approximately square images or the bottom portion of your picture will be automatically cropped out', null=True, upload_to='gallery_pics'),
        ),
    ]
