# Generated by Django 3.0.3 on 2020-09-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200820_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invitations_sent',
            field=models.ManyToManyField(blank=True, related_name='invitations_sent', to='users.Relationship'),
        ),
    ]
