# Generated by Django 3.0.3 on 2020-10-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_invitations_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target_audience',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, help_text='mm/dd/yyyy: make sure to fill this field out for the best user experience!', null=True),
        ),
    ]
