# Generated by Django 3.0.3 on 2020-10-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20201027_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, help_text='mm/dd/yyyy: make sure to fill this field out for the best user experience! To hide your age, leave this blank.', null=True),
        ),
    ]
