# Generated by Django 3.0.3 on 2021-04-10 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20201027_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bible_verse',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='denomination',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_animal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagramtag',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='invitations_sent',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='relationship_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='target_audience',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='testimony',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tiktoktag',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
